### ISSUE TITLE
BioCParallel errors

### ISSUE THREAD

**Issue by ghost** [GaelleLefort/ASICS#3]
Hi there @GaelleLefort,

I've been getting these error message to align the peaks and calculate metabolite concentration using the code, tried it using different devices and they all yield similar output, with BiocParallel errors. 

`Remove areas from spectrum and library 
  |=================================================================================================| 100%

Compute weights 
  |=================================================================================================| 100%

Remove metabolites that cannot belong to the mixture 
  |=================================================================================================| 100%

Translate library 
Compute shifts for all maximum shift values 
  |===================                                                                              |  20%

Error: BiocParallel errors
  1 remote errors, element index: 1
  4 unevaluated and other errors
  first remote error:
Error in (function (cl, name, valueClass) : assignment of an object of class “ldiMatrix” is not valid for @‘spectra’ in an object of class “PureLibrary”; is(value, "generalMatrix") is not TRUE`

Another BioCParallel errors:
Error: BiocParallel errors
  1 remote errors, element index: 1
  188 unevaluated and other errors
  first remote error:
Error in .local(x, i, j, ..., value): not-yet-implemented 'Matrix[<-' method

Do you have any idea what would be the reason for this error please? Any help is much appreciated!

**Comment by tuxette** [comment]
Can you provide a minimal example (with data) along with your R session information (output of sessionInfo())? If you can not provide them publicly, feel free to send them by email. Contact information is available here: http://www.nathalievialaneix.eu/

**Comment by tuxette** [comment]
Thanks for the dataset that you sent. I ran:
```
current_path = "NMR_Spectra_test_5samples"
spectra_data <- importSpectraBruker(current_path)
spectra_obj <- createSpectra(spectra_data)
resASICS <- ASICS(spectra_obj, exclusion.areas = to_exclude, verbose = TRUE)
```
and also
```
resASICS <- ASICS(spectra_obj, exclusion.areas = to_exclude, verbose = TRUE, ncores = 2)
```
and I am not able to reproduce your error, with the same **R** version and almost the same package versions. Is that what you tried to do? Can you switch `ncores` from 1 to 2 or the other way around to check if the problem comes from there. I can send you the result of that computation but it does not help much.

**Comment by tuxette** [comment]
If you ran these code lines, please, try this:
- send me `spectra_obj` (`save(spectra_obj, file = "spectra.rda")` and send me `spectra.rda`);
- reinstall `tidyverse` (and restart **R**).

**Comment by ghost** [comment]
Thanks for the reply! I did 

`spectra_norm <- normaliseSpectra(spectra_data, type.norm = "CS")`
`spectra_align <- alignSpectra(spectra_norm)`

before doing 

`spectra_obj <- createSpectra(spectra_align)`
`ASICS_results <- ASICS(spectra_obj, exclusion.areas = to_exclude)`

I am suspecting the issues arised after normalising and aligning. Please also see my spectra_obj file as attached in the email as Github does not support rda file type.

**Comment by tuxette** [comment]
Hi @chuiyangmok 
Sorry for the time it took me to check your data. I'm not posting the images here but the problem comes from the data and not from the package: you have an abnormal huge negative peak in the middle of your spectra. ASICS is a deconvolution method that expects to have mostly positive spectra (small negative parts can happen due to noise but when the signal is mostly negative, it indicates a problem in the spectrum preprocessing). I'm sending you the images and the code by email.
